// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.IdentityAuth;

[Table("RolePermission")]
public partial class RolePermission : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    public string Method { get; set; }

    public string MethodDescription { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    [InverseProperty("RolePermission")]
    public virtual ICollection<RoleClaim> RoleClaims { get; set; } = new List<RoleClaim>();
}