// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.IdentityAuth;

[Table("RoleClaim")]
public partial class RoleClaim : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public Guid? RoleId { get; set; }

    public Guid? RolePermissionId { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("RoleClaims")]
    public virtual Role Role { get; set; }

    [ForeignKey("RolePermissionId")]
    [InverseProperty("RoleClaims")]
    public virtual RolePermission RolePermission { get; set; }
}