// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.IdentityAuth;

[Table("UserPermission")]
public partial class UserPermission : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    public string UserAccess { get; set; }

    public string UserAccessDescription { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    [InverseProperty("UserPermition")]
    public virtual ICollection<UserClaim> UserClaims { get; set; } = new List<UserClaim>();
}