// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Models;
using System;
using System.Collections.Generic;
using System.Reflection;

namespace Sparrow.Persistence.Contexts.MusicDbContext;

public partial class Music_DbContext : DbContext
{
    public Music_DbContext(DbContextOptions<Music_DbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Album> Albums { get; set; }

    public virtual DbSet<Artist> Artists { get; set; }

    public virtual DbSet<ArtistAlbum> ArtistAlbums { get; set; }

    public virtual DbSet<Music> Musics { get; set; }

    public virtual DbSet<MusicAlbum> MusicAlbums { get; set; }

    public virtual DbSet<Playlist> Playlists { get; set; }

    public virtual DbSet<PlaylistMusic> PlaylistMusics { get; set; }

    public virtual DbSet<PlaylistUser> PlaylistUsers { get; set; }

    public virtual DbSet<Radio> Radios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}