// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sparrow.Persistence.Contexts.MusicDbContext;

#nullable disable

namespace Sparrow.Persistence.Migrations
{
    [DbContext(typeof(Music_DbContext))]
    [Migration("20260604124905_SparrowContextMigration1")]
    partial class SparrowContextMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAlbum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageArtist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.ArtistAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId_forArtistAlbum")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId_forArtistAlbum")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId_forArtistAlbum");

                    b.HasIndex("ArtistId_forArtistAlbum");

                    b.ToTable("ArtistAlbum");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.Music", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageMusic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusicFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isPopularMusic")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Music");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.MusicAlbum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlbumId_forMusicAlbum")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicId_forMusicAlbum")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId_forMusicAlbum");

                    b.HasIndex("MusicId_forMusicAlbum");

                    b.ToTable("MusicAlbum");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePlaylist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaylistDatetime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaylistDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.PlaylistMusic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusicId_forPlaylistMusic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaylistId_forPlaylistMusic")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MusicId_forPlaylistMusic");

                    b.HasIndex("PlaylistId_forPlaylistMusic");

                    b.ToTable("PlaylistMusic");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.PlaylistUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlaylistId_forPlaylistUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId_forPlaylistUser")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId_forPlaylistUser");

                    b.ToTable("PlaylistUser");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.Radio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageRadio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadioCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadioDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadioFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadioName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Radio");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.ArtistAlbum", b =>
                {
                    b.HasOne("Sparrow.Domain.Entities.Models.Album", "AlbumId_forArtistAlbumNavigation")
                        .WithMany("ArtistAlbums")
                        .HasForeignKey("AlbumId_forArtistAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sparrow.Domain.Entities.Models.Artist", "ArtistId_forArtistAlbumNavigation")
                        .WithMany("ArtistAlbums")
                        .HasForeignKey("ArtistId_forArtistAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumId_forArtistAlbumNavigation");

                    b.Navigation("ArtistId_forArtistAlbumNavigation");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.MusicAlbum", b =>
                {
                    b.HasOne("Sparrow.Domain.Entities.Models.Album", "AlbumId_forMusicAlbumNavigation")
                        .WithMany("MusicAlbums")
                        .HasForeignKey("AlbumId_forMusicAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sparrow.Domain.Entities.Models.Music", "MusicId_forMusicAlbumNavigation")
                        .WithMany("MusicAlbums")
                        .HasForeignKey("MusicId_forMusicAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlbumId_forMusicAlbumNavigation");

                    b.Navigation("MusicId_forMusicAlbumNavigation");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.PlaylistMusic", b =>
                {
                    b.HasOne("Sparrow.Domain.Entities.Models.Music", "MusicId_forPlaylistMusicNavigation")
                        .WithMany("PlaylistMusics")
                        .HasForeignKey("MusicId_forPlaylistMusic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sparrow.Domain.Entities.Models.Playlist", "PlaylistId_forPlaylistMusicNavigation")
                        .WithMany("PlaylistMusics")
                        .HasForeignKey("PlaylistId_forPlaylistMusic")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicId_forPlaylistMusicNavigation");

                    b.Navigation("PlaylistId_forPlaylistMusicNavigation");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.PlaylistUser", b =>
                {
                    b.HasOne("Sparrow.Domain.Entities.Models.Playlist", "PlaylistId_forPlaylistUserNavigation")
                        .WithMany("PlaylistUsers")
                        .HasForeignKey("PlaylistId_forPlaylistUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaylistId_forPlaylistUserNavigation");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.Album", b =>
                {
                    b.Navigation("ArtistAlbums");

                    b.Navigation("MusicAlbums");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.Artist", b =>
                {
                    b.Navigation("ArtistAlbums");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.Music", b =>
                {
                    b.Navigation("MusicAlbums");

                    b.Navigation("PlaylistMusics");
                });

            modelBuilder.Entity("Sparrow.Domain.Entities.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistMusics");

                    b.Navigation("PlaylistUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
