// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;

namespace Sparrow.Domain.Entities.Models;

[Table("Album")]
public partial class Album:BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string AlbumName { get; set; }

    [Required]
    public string ImageAlbum { get; set; }

    [InverseProperty("AlbumId_forArtistAlbumNavigation")]
    public virtual ICollection<ArtistAlbum> ArtistAlbums { get; set; } = new List<ArtistAlbum>();

    [InverseProperty("AlbumId_forMusicAlbumNavigation")]
    public virtual ICollection<MusicAlbum> MusicAlbums { get; set; } = new List<MusicAlbum>();
}