// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.Models;

[Table("Artist")]
public partial class Artist : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string ArtistName { get; set; }

    [Required]
    public string ImageArtist { get; set; }

    [InverseProperty("ArtistId_forArtistAlbumNavigation")]
    public virtual ICollection<ArtistAlbum> ArtistAlbums { get; set; } = new List<ArtistAlbum>();
}