// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.Models;

[Table("ArtistAlbum")]
public partial class ArtistAlbum : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    public Guid ArtistId_forArtistAlbum { get; set; }

    public Guid AlbumId_forArtistAlbum { get; set; }

    [ForeignKey("AlbumId_forArtistAlbum")]
    [InverseProperty("ArtistAlbums")]
    public virtual Album AlbumId_forArtistAlbumNavigation { get; set; }

    [ForeignKey("ArtistId_forArtistAlbum")]
    [InverseProperty("ArtistAlbums")]
    public virtual Artist ArtistId_forArtistAlbumNavigation { get; set; }
}