// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.Models;

[Table("Music")]
public partial class Music : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string MusicName { get; set; }

    public bool isPopularMusic { get; set; }

    [Required]
    public string ImageMusic { get; set; }

    [Required]
    public string MusicFile { get; set; }

    [InverseProperty("MusicId_forMusicAlbumNavigation")]
    public virtual ICollection<MusicAlbum> MusicAlbums { get; set; } = new List<MusicAlbum>();

    [InverseProperty("MusicId_forPlaylistMusicNavigation")]
    public virtual ICollection<PlaylistMusic> PlaylistMusics { get; set; } = new List<PlaylistMusic>();
}