// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.Models;

[Table("MusicAlbum")]
public partial class MusicAlbum : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    public Guid MusicId_forMusicAlbum { get; set; }

    public Guid AlbumId_forMusicAlbum { get; set; }

    [ForeignKey("AlbumId_forMusicAlbum")]
    [InverseProperty("MusicAlbums")]
    public virtual Album AlbumId_forMusicAlbumNavigation { get; set; }

    [ForeignKey("MusicId_forMusicAlbum")]
    [InverseProperty("MusicAlbums")]
    public virtual Music MusicId_forMusicAlbumNavigation { get; set; }
}