// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.Models;

[Table("Playlist")]
public partial class Playlist : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string PlaylistName { get; set; }

    [Required]
    public string PlaylistDescription { get; set; }

    [Required]
    public string PlaylistDatetime { get; set; }

    [Required]
    public string ImagePlaylist { get; set; }

    [InverseProperty("PlaylistId_forPlaylistMusicNavigation")]
    public virtual ICollection<PlaylistMusic> PlaylistMusics { get; set; } = new List<PlaylistMusic>();

    [InverseProperty("PlaylistId_forPlaylistUserNavigation")]
    public virtual ICollection<PlaylistUser> PlaylistUsers { get; set; } = new List<PlaylistUser>();
}