// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.Models;

[Table("PlaylistMusic")]
public partial class PlaylistMusic : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    public Guid PlaylistId_forPlaylistMusic { get; set; }

    public Guid MusicId_forPlaylistMusic { get; set; }

    [ForeignKey("MusicId_forPlaylistMusic")]
    [InverseProperty("PlaylistMusics")]
    public virtual Music MusicId_forPlaylistMusicNavigation { get; set; }

    [ForeignKey("PlaylistId_forPlaylistMusic")]
    [InverseProperty("PlaylistMusics")]
    public virtual Playlist PlaylistId_forPlaylistMusicNavigation { get; set; }
}