// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.Models;

[Table("PlaylistUser")]
public partial class PlaylistUser : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    public Guid UserId_forPlaylistUser { get; set; }

    public Guid PlaylistId_forPlaylistUser { get; set; }

    [ForeignKey("PlaylistId_forPlaylistUser")]
    [InverseProperty("PlaylistUsers")]
    public virtual Playlist PlaylistId_forPlaylistUserNavigation { get; set; }
}