// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Sparrow.Domain.Entities.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sparrow.Domain.Entities.Models;

[Table("Radio")]
public partial class Radio : BaseEntity
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string RadioName { get; set; }

    [Required]
    public string ImageRadio { get; set; }

    [Required]
    public string RadioFile { get; set; }

    [Required]
    public string RadioDescription { get; set; }

    [Required]
    public string RadioCountry { get; set; }
}